### ISSUE TITLE
Bad results with my own dataset

### ISSUE THREAD

**Issue by Saji70** [tudelft3d/3dfier#134]
Dear 3Dfiers

I used 3Dfier in my thesis but the result with my own dataset did not look good. I attached my sample dataset here. Would you please give me guides to solve the problem?

[test_data.zip](https://github.com/tudelft3d/3dfier/files/6602124/test_data.zip)

**Comment by balazsdukai** [comment]
Dear @Saji70 , generally speaking, in order to get good results with 3dfier, your input polygons should be topologically correct and the polygons and the point cloud needs to be well aligned. Apart of that, you can try the various settings for the object types, particularly those ones that are related to vertex buffers and simplification. There is an extensive documentation where you'll find the details: http://tudelft3d.github.io/3dfier/
