### ISSUE TITLE
OBJ export broken?

### ISSUE THREAD

**Issue by surfsara-visualization** [tudelft3d/3dfier#20]
Hi, after Tom's talk at the 3D Symposium earlier this week I decided to give 3dfier a go. With the included example_data CityGML output is generated correctly, but when I change the format to OBJ in the yaml file 3dfier crashes. I did a bit of debugging and it seems that in Map3d::get_obj_per_feature(int) one of the keys in thepts is the empty string in my case. This causes std::stof to raise an exception, as it can't convert anything. I added a check to skip the empty string (see patch below), but although I now get an output OBJ file it doesn't seem to be correct (and doesn't load in e.g. MeshLab). Some faces use vertex indices that are out of range. I.e.

```
$ ../build/3dfier testarea_config.yml > out.obj
...
$ grep "^v " out.obj |wc -l
14608     # valid vertex indices 1..14608
$ tail out.obj 
f 9460 9459 14598
f 14598 9459 14606
f 9951 9460 14608
f 14608 9460 14598
f 14094 9952 14609 <<< out of range
f 14609 9952 9951 <<< out of range
f 14609 9951 14608 <<< out of range
f 14095 14094 14610 <<< out of range
f 14610 14094 14609 <<< out of range
```

This is on Arch Linux, 64-bit, GCC 6.2.1. 

```
diff --git a/Map3d.cpp b/Map3d.cpp
index a2193e3..ec6cc72 100644
--- a/Map3d.cpp
+++ b/Map3d.cpp
@@ -198,6 +198,8 @@ std::string Map3d::get_obj_per_feature(int z_exaggeration) {
   ss << "mtllib ./3dfier.mtl" << std::endl;
   ss << std::setprecision(3) << std::fixed;
   for (auto& p : thepts) {
+    if (p.length() == 0)
+        continue;
     ss << "v ";
     ss << (std::stof(p.substr(0, p.find_first_of("/")))) / 100 << " ";
     ss << (std::stof(p.substr(p.find_first_of("/") + 1, p.find_last_of("/")))) / 100 << " ";
```

**Comment by tcommandeur** [comment]
Hi, great to hear that you started using 3dfier! Thank you for letting us know about this bug, we have heard about this last week and we found the issue today. It is a bit more difficult as just "the one of the keys in thepts is the empty string". The Arch Linux GCC compiler uses a different optimization then the Windows and MacOSX one and therefor the bug was not noticed before. 
The issue lies in TopoFeature::get_obj() -> "dPts[gen_key_bucket(&_vertices[t.v1])] = dPts.size() + 1;" where the GCC compiler favors the creation of the hash over the dPts.size() command and such the index stored in the array is one too large.

Sort version: we fixed the issue and optimized the writing of OBJ's in the obj_output_bug branch which we will merge with the master branch soon.
