### ISSUE TITLE
Error: missing height field

### ISSUE THREAD

**Issue by christianbraun** [tudelft3d/3dfier#37]
Dear all,
I get the following error at the beginning of the 3dfying:

ERROR: field 'hoogtenive' not found in layer 'buildings_overground', using all polygons.
	Layer: buildings_overground
	(6,779 features --> Building)

A result is generated but the result is missing 3D heights, obviously.

3dfier build as 0.9.7 on macOS

Thanks in advance,
Christian

**Comment by tcommandeur** [comment]
This error occurs if there is no attribute describing different height level (like fly-overs being a higher level in a road network) and continues using all polygons. This error doesn't have anything to do with not generating heights.

Are you certain the las/laz files and polygon files lay on top of each other?

Can you otherwise post the configuration here?

**Comment by christianbraun** [comment]
thanks, I solved the issue
