### ISSUE TITLE
Generating bridges as slanted objects?

### ISSUE THREAD

**Issue by CarolMrx** [tudelft3d/3dfier#72]
When applying the 3Dfier (using version 0.9.7) on our 2D data the bridges are generally generated as horizontal surfaces. Is there already any enhancement / upgrade for the 3Dfier, so that the bridges can be modelled as slanted objects in order to connect the two adjacent streets continuously (like a linear interpolation)?
That would be quite interesting for us, as we are modelling a 3D landscape model in a region of the Bavarian / Austrian Alps with partly quite big elevation differences.
(see pic1 - pic3.png)

![pic1](https://user-images.githubusercontent.com/28733971/42379925-85881ec8-812c-11e8-9caf-5343e5877330.png)
![pic2](https://user-images.githubusercontent.com/28733971/42379944-898d2dc4-812c-11e8-9fcd-e63527a8a270.png)
![pic3](https://user-images.githubusercontent.com/28733971/42379947-8e41b894-812c-11e8-8fb7-fad7260ed1cf.png)

Did you also consider cases, when 2 bridges are overlapping each other? See e.g. pic4.png (the green bridge should be modelled above the little dark grey bridge)

![pic4](https://user-images.githubusercontent.com/28733971/42379957-9596ae4c-812c-11e8-86fb-0113590a6df1.png)

Thanks for your help!

**Comment by tcommandeur** [comment]
Hi Carol,

The most recent version 1.0 RC2 still models bridges like that. Creating bridges is a difficult thing since there is a floating object with a height jump on the sides and also (normally) no point cloud thus height information available underneath. 

As this moment we are working hard on making the bridges work as 3DBoundary objects instead of flat objects.

As for the last case, we know these are there but the focus is at normal bridges at this time (where a road overpasses a road) and not multiple heights like complex crossings with multiple fly-overs. This will be taken into account once work on bridges are finished.

We expect the next release to have better bridges included.
