### ISSUE TITLE
Cropping laz/las

### ISSUE THREAD

**Issue by LirryPinter** [tudelft3d/3dfier#81]
Hi,

Great code! I have one question: what method do you people use for the cropping for the laz/las files? Also, why do you use 2? When im downloading data from BGT everything is fine, but as you know the PDOK laz files are based on the BRT background map. For some reason I cant get any height into my 3dfied objects, I think because the extends dont match.

Thanks,

**Comment by balazsdukai** [comment]
Hi,
could you clarify your question a bit? Is there any combination of data sets that give you the desired results, or nothing works at all? Are you using BGT or BRT as 2D input?
What do you mean by "Also, why do you use 2?" ?

In general, the extend of the laz files and the 2D polygons need to overlap, otherwise the polygons are simply output without height.
The point cloud is not cropped at all. For each polygon, the laz file is searched to find the points that overlap with the polygon.

**Comment by LirryPinter** [comment]
Hi! Thanks for answering. 
I am using the BGT, and AHN3. The only time it worked with a height was with the example data. And in the example 2 laz files are being used, hence the question! 

The geometry/area of the AHN3 Laz file i downloaded (PDOK) was bigger then the 2D polygons of the BGT. 
So I am not really sure what I am doing wrong, if I am correct all the 2D polygons would be findable in the AHN3 Laz file..

**Comment by balazsdukai** [comment]
If you are using the BGT as it is downloaded from PDOK, then it needs to be prepared. Yes, this it not really clear from the documentation. Look into the readme and files here: https://github.com/tudelft3d/3dfier/tree/master/resources/BGT_prepare , and let me know if it solves your problem.

If that doesn't solve your problem, then please send me a small subset of the BGT that you are using as input and the 3dfier configuration file (the .yml file).
