### ISSUE TITLE
SRS always epsg 7415

### ISSUE THREAD

**Issue by vvmruder** [tudelft3d/3dfier#90]
I know this issue doubles this one:
https://github.com/tudelft3d/3dfier/issues/86

3dfier does not respect the input data SRS nor offers a configuration to set output SRS straight. While this means a lot of code writing it would be somewhat useful.

But I think it should be possible to use non dutch projections with 3dfier.

I could offer help on that if needed.

**Comment by tcommandeur** [comment]
The issue is embedded deeper then taking the SRS and and set the output SRS. 

In the core of 3dfier we use integer storage for the coordinates by multiplying it by 1000. When creating the 3D objects we reconstruct by division by 1000 to get back to the original coordinates. This gives us millimeter accuracy. When using anything other then projected coordinate systems in meters this approach doesn't work. For example an WGS84 projection would be rounded to 3 decimals resulting in about 100 meter accuracy for latitude coordinates.

The original coordinates are kept anyhow so only the metadata describing the SRS is wrong. If there is any way to easily limit coordinate systems to a set of projected we can make it work. Otherwise we just ignore the SRS and write the dutch SRS.
